name: Deploy

on: [push]

jobs:
  deploy:
    name: Deploy my app

    runs-on: ubuntu-latest

    permissions:
      deployments: write

    steps:
      - uses: actions/checkout@v1
      - name: Retrieve version
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        run: |
          echo ::set-env name=LAST_COMMIT::$(git --no-pager show -s --format="%s")


      - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment
        id: deployment
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        with:
          token: '${{ github.token }}'
          environment-url: $(git --no-pager show -s --format="%s")
          environment: production
          description: ${{ env.TAG_NAME }}
